# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d05fab00698ed71c5220418ead3e22e0e720ef744020c41ae8d55987f02315bf1ee451bf4381509f5d870829e687ac842f7f50b5ede279208238dd76c6af2112

test:
  secret_key_base: 101ad8f863eba866733d02df0225010dbad1e7078c7411ab98fe7abec76e44e42856448b4f075b86596864edc81cfb5bfd618d3502df765e9a80ef7dcc2ad624

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
